### ISSUE TITLE
"i want to be banned from github?" type of issue

### ISSUE THREAD

**Issue by NikitaBuyanov** [themaoci/DeathDot-csgo-#2]
Why are u using writeprocessmemory/readprocessmemory in an internal cheat? lmao just write to memory directly dumbfuck

`*(int*)(*Entity + offset) = DesiredValue;`

Here take this:

https://www.learncpp.com/cpp-tutorial/67-introduction-to-pointers/

**Comment by themaoci** [comment]
"internal" doesnt tell you anything ... it was a inside meme i made with few friends ... lmao
